[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 800
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
gas_reports = ["TruglyLaunchpad", "TruglyLaunchpadTest", "TruglyUniversalRouterBaseTest", "TruglyUniversalRouter"]
# cancun = true
via_ir = true

[profile.default.fuzz]
runs = 1000
seed = "0x2121"

[profile.ci.fuzz]
runs = 100000

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
base = "${RPC_BASE}"
mumbai="${RPC_MUMBAI}"

[etherscan]
goerli={key="${ETHERSCAN_GOERLI_API_KEY}"}
base={key="${ETHERSCAN_BASE_API_KEY}"}
base_sepolia={key="${ETHERSCAN_BASE_SEPOLIA_API_KEY}"}
sepolia={key="${ETHERSCAN_GOERLI_API_KEY}"}
mumbai={key="${ETHERSCAN_MUMBAI_API_KEY}"}


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

